### ISSUE TITLE
More efficient GPU compute

### ISSUE THREAD

**Issue by ieivanov** [mehta-lab/waveorder#58]
Most of the QLIPP compute functions take the same variables in and out of GPU memory, which is inefficient. 

For example, `Stokes_transform` put the raw Stokes images into GPU memory, carries out the Stokes normalization, and takes the normalized Stokes parameters out of GPU memory; `Polscope_bg_correction` then puts the normalized Stokes images back into GPU memory to carry out the background normalization math, and takes the background corrected Stokes images out of GPU memory at the end. 

A more efficient way to process a single z-stack would be something like this:

```
reconstructor.Stokes_recon(I_meas) ## here I_meas is YXZ stack; raw Stokes images stay in GPU memory

reconstructor.Stokes_transform() ## normalize raw Stokes images which are in GPU memory and keep them there

reconstructor.Polscope_bg_correction(S_bg) ## pass a single argument with background Stokes images; these can stay in GPU memory for reuse or be rewritten is new S_bg are passed next time the function is called

phys_props = reconstructor.Polarization_recon() ## recon phys props with bg corrected Stokes in GPU memory

phase = reconstructor.Phase_recon_3D(method='Tikhonov') ## recon phase with S[0] from GPU memory
```

We'll need to make sure that the reconstruction still works as expected if these steps are not followed in order. For example, calling reconstructor.Stokes_recon should erase old S_norm, S_corr, etc. from GPU memory. Recon functions can still return the expected output variables such that intermediate results can be inspected. The Stokes input parameters to `Stokes_transform`, `Polscope_bg_correction`, `Polarization_recon`, and `Phase_recon_3D` should be optional, such that, for example, Stokes parameters can be processed (e.g. denoised, filtered, averaged) outside of the reconstructor before plugging them back in the pipeline.

**Comment by lihaoyeh** [comment]
I am aware of this when initially writing up these functions. There are a two reasons why I end up choosing to do so. 

First, GPU memory handling with class variables in jupyter may not be optimal. The GPU memory will not be automatically freed up even though the GPU array is reassigned to something else. Deleting the class in the notebook also does not free up the GPU memory. That's why I keep all of the GPU array assignments in the class methods. When I finished using the GPU array, I clean it right away in the method. Even so, there is still some accumulation needed to be sorted out. Doing so ensures that the memory stays as clean as possible for other processes. Otherwise, careless accumulation of the memory space tends to limit the computational capacity. This might not be a major concern if we do not use jupyter often.

Second, taking arrays in and out of the GPU memory takes much less time than the actual computation. I have profiled these operations before. Removing these in-and-out operations does save time but it is marginal to the overall computation time.

**Comment by ieivanov** [comment]
> Second, taking arrays in and out of the GPU memory takes much less time than the actual computation. I have profiled these operations before. Removing these in-and-out operations does save time but it is marginal to the overall computation time.

Ah, that's good to know, thanks for explaining.
